name: Daily Summary Test

on:
  workflow_dispatch:

jobs:
  test-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy source file into summary file
        run: |
          summary=$(cat kb-source/notice-management-update.md)
          echo "$summary" > kb-summaries/daily-summary.md

      - name: Save updated summary file back to GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add kb-summaries/daily-summary.md
          git commit -m "Update daily summary" || echo "No changes to commit"
          git push
